### ISSUE TITLE
errbot fails to see that a message is coming from itself

### ISSUE THREAD

**Issue by gbin** [errbotio/err-backend-gitter#1]
try: (with err-ascii-art and err-codebot plugins)

```
!python print("!big " + chr(int('01010010',2)) + chr(int('00110010',2)))
```

and the bot will happily do that:

![image](https://cloud.githubusercontent.com/assets/975564/9232422/6800e9ee-40e2-11e5-9ce9-f558cba98c0d.png)

**Comment by zoni** [comment]
Fixed by 2ecfaf49ea815b5c3545dae157be083cd7b47cdc.
